_target_: vox2vec.eval.datamodules.lidc.LIDCDataModule
lidc_dirpath: ${paths.prepared_data_dirs.lidc}
crop_size: [128, 128, 64]
batch_size: 8
num_batches_per_epoch: 300
num_workers: 8
val_size: 100
train_size: 1.0
random_seed: 42