defaults:
  - pretrain_data_fractions: default
  - color_augmentations: default

_target_: vox2vec.pretrain.datamodules.mim.MIMDataModule
prepared_data_dirs: ${paths.prepared_data_dirs}
nlst_val_size: 1000
target_crop_size: [192, 192, 96]
context_crop_size: [160, 160, 80]
token_size_per_scale: [[4, 4, 2], [8, 8, 4], [16, 16, 8], [32, 32, 16]]
num_blocks_per_scale: [512, 64, 8, 1]
max_block_aspect_ratio: 1.5
mask_ratio_range: [0.6, 0.8]
batch_size: 4
num_batches_per_epoch: 3000
num_workers: 8
random_seed: 42