defaults:
  - pretrain_data_fractions: default
  - color_augmentations: default

_target_: vox2vec.pretrain.datamodules.moco.MoCoDataModule
prepared_data_dirs: ${paths.prepared_data_dirs}
spatial_augmentations:
  context_min_voxel_spacing: [1.0, 1.0, 2.0]
  context_max_voxel_spacing: [2.0, 2.0, 4.0]
  context_crop_size: [64, 64, 32]
  target_crop_size: [128, 128, 64]
num_voxels_per_crop: 512
batch_size: 4
num_batches_per_epoch: 3000
num_workers: 8
nlst_val_size: 1000
random_seed: 42