_target_: medimm.fpn_3d.FPN3d
in_channels: 1
stem_stride: [4, 4, 2]
out_channels: [192, 384, 768, 1536]
hidden_factors: 4.0
depths: [[3, 1], [3, 1], [27, 1], 3]
stem_kernel_size: [4, 4, 2]
stem_padding: 0
drop_path_rate: 0.1
final_ln: true
final_affine: false
final_gelu: false
mask_token: True