_target_: medimm.fpn_3d.FPN3d
in_channels: 1
stem_stride: [4, 4, 2]
out_channels: [128, 256, 512, 1024]
depths: [[2, 1], [2, 1], [26, 1], 3]
stem_kernel_size: null
stem_padding: null
drop_path_rate: 0.1
final_ln: true
final_affine: false
final_gelu: false
mask_token: True