_target_: vox2vec.nn.unet_3d.UNet3d
in_channels: 1
stem_stride: [4, 4, 2]
out_channels: 128
fpn_out_channels: [128, 256, 512, 1024]
fpn_depths: [[3, 1], [3, 1], [27, 1], 3]
stem_kernel_size: [4, 4, 2]
stem_padding: 0
drop_path_rate: 0.1
final_ln: true
final_affine: false
final_gelu: false
mask_token: true