_target_: vox2vec.nn.unet_3d.UNet3d
in_channels: 1
stem_stride: [3, 3, 2]
out_channels: 96
fpn_out_channels: [96, 192, 384, 768]
fpn_hidden_factors: 4.0
fpn_depths: [[3, 1], [3, 1], [9, 1], 3]
stem_kernel_size: [3, 3, 2]
stem_padding: 0
drop_path_rate: 0.0
final_ln: false
final_affine: false
final_gelu: false
mask_token: true