defaults:
  - preprocessing: default
  - paths: default
  - hydra: no_outputs
  - _self_


# filtering params
min_series_length: 96
max_voxel_spacing: [1.0, 1.0, 5.0]
min_image_size: [192, 192, 96]

num_workers: 16