defaults:
  - preprocessing: default
  - paths: default
  - hydra: no_outputs
  - _self_


# filtering params
min_series_length: 112
max_voxel_spacing: [1.0, 1.0, 2.5]
min_image_size: [224, 224, 112]

num_workers: 16