defaults:
  - pretrain_datamodule: simclr
  - backbone: unet_fullres
  - heads/unet_linear
  - heads/unet_nonlinear
  - pretrain_model: moco_unet
  - trainer: default
  - paths: default
  - hydra: default
  - _self_


pretrain_datamodule:
  pretrain_data_fractions:
    nlst: 1.0
    amos_ct_labeled_train: 0.0
    amos_ct_unlabeled_train: 0.0
    abdomen_atlas: 0.0
    flare23_labeled_train: 0.0
    flare23_unlabeled_train: 0.0
  batch_size: 4

backbone:
  final_ln: false

heads:
  linear:
    out_channels: 1
  nonlinear:
    out_channels: 1

online_probing:
  crop_size: [128, 128, 64]
  batch_size: 4
  num_workers: 4

ckpt_path: null

logs_group: pretrain/moco_unet