defaults:
  - pretrain_datamodule: mim
  - backbone: fpn_base
  - heads/fpn_linear
  - heads/fpn_nonlinear
  - pretrain_model: mim
  - trainer: default
  - paths: default
  - hydra: default
  - _self_


heads:
  linear:
    out_channels: 1
  nonlinear:
    out_channels: 1

online_probing:
  crop_size: [192, 192, 96]
  batch_size: 4
  num_workers: 4

ckpt_path: null

logs_group: pretrain/mim