_target_: vox2vec.pretrain.models.mim.MIM
backbone: ${backbone}
pred_hidden_factor: 0.25
pred_depth: 3
pred_kernel_size: 7
base_tau: 0.996
final_tau: 1.0
lr: 0.0003
weight_decay: 0.000001
warmup_steps: 10_000
total_steps: ${trainer.max_steps}