_target_: vox2vec.pretrain.models.mim.MIM
backbone: ${backbone}
proj_hidden_factor: 4.0
proj_out_dim: 128
pred_hidden_factor: 1.0
pred_depth: 3
pred_kernel_size: 5
base_tau: 0.996
final_tau: 1.0
lr: 0.01
weight_decay: 0.000001
warmup_steps: 10_000
total_steps: ${trainer.max_steps}