_target_: vox2vec.pretrain.models.moco_unet.MoCoUNet
backbone: ${backbone}
proj_hidden_dim: 512
proj_out_dim: 128
pred_hidden_dim: 512
temp: 0.1
queue_size: 1048576
mask_targets: false
tau: 0.999
lr: 0.01
weight_decay: 0.000001
warmup_steps: 10_000
total_steps: ${trainer.max_steps}