_target_: vox2vec.pretrain.models.simclr_unet.SimCLRUNet
backbone: ${backbone}
proj_hidden_dim: 2048
proj_out_dim: 128
temp: 0.1
lr: 0.01
weight_decay: 0.000001
warmup_steps: 10_000
total_steps: ${trainer.max_steps}