_target_: vox2vec.pretrain.models.unbiased_vicreg.UnbiasedVICReg
backbone: ${backbone}
proj_hidden_dim: 8192
proj_out_dim: 8192
i_weight: 25.0
v_weight: 25.0
c_weight: 1.0
lr: 0.0001
weight_decay: 0.000001
warmup_steps: 10_000
total_steps: ${trainer.max_steps}